/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jld_obdserialport_SerialPortDevice */

#ifndef _Included_com_jld_obdserialport_SerialPortDevice
#define _Included_com_jld_obdserialport_SerialPortDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jld_obdserialport_SerialPortDevice
 * Method:    helloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jld_obdserialport_SerialPortDevice_helloJni
  (JNIEnv *, jclass);

/*
 * Class:     com_jld_obdserialport_SerialPortDevice
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jld_obdserialport_SerialPortDevice_close
  (JNIEnv *, jobject);

/*
 * Class:     com_jld_obdserialport_SerialPortDevice
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_jld_obdserialport_SerialPortDevice_open
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
